-- Create the 'alerts' table to store anomalies detected by Pathway
create table public.alerts (
  id uuid default gen_random_uuid() primary key,
  sensor_id text not null,
  temperature double precision,
  vibration double precision,
  timestamp bigint,
  repair_action text, -- Generated by Gemini
  created_at timestamptz default now()
);

-- Enable Realtime for this table so the frontend can subscribe to INSERT events
alter publication supabase_realtime add table public.alerts;

-- Optional: Create an index on timestamp for faster queries
create index idx_alerts_timestamp on public.alerts(timestamp desc);
